name: Test API

on:
  push:
    branches:
      - master  # Déclenchement lors d'un push sur la branche master
  pull_request:
    branches:
      - master  # Déclenchement lors d'une pull request vers master

jobs:
  test:
    runs-on: ubuntu-latest  # Utilise l'image Ubuntu la plus récente sur GitHub Actions

    steps:
      # 1. Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurer Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # Spécifie la version de Python que tu veux utiliser

      # 3. Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installe les dépendances spécifiées dans requirements.txt

      # 4. Vérifier les fichiers présents (facultatif pour débogage)
      - name: Vérifier les fichiers présents
        run: |
          ls -al  # Liste les fichiers du répertoire courant

      # 5. Exécuter les tests avec pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings  # Exécute pytest avec des options pour arrêter après un échec et désactiver les avertissements


