name: Tests API

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check pandas version
        run: |
          python -m pip show pandas
          python -m pip show fastapi
          python -m pip show lightgbm
          python -m pip show pytest

      - name: List installed packages
        run: |
          pip freeze

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings test_unitaire_api.py

